[[redirects]]
  from = "/v1/*"
  to = "http://ec2-18-118-138-187.us-east-2.compute.amazonaws.com/v1/:splat"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "http://ec2-18-118-138-187.us-east-2.compute.amazonaws.com/admin/:splat"
  status = 200

[[redirects]]
  from = "/static/media/uploads/*"
  to = "http://ec2-18-118-138-187.us-east-2.compute.amazonaws.com/static/media/uploads/:splat"
  status = 200

[[redirects]]
  from = "/static/static/*"
  to = "http://ec2-18-118-138-187.us-east-2.compute.amazonaws.com/static/static/:splat"
  status = 200

[[redirects]]
  from = "/vol/web/*"
  to = "http://ec2-18-118-138-187.us-east-2.compute.amazonaws.com/vol/web/:splat"
  status = 200

