[[redirects]]
  from = "/v1/*"
  to = "http://ec2-18-118-138-187.us-east-2.compute.amazonaws.com/api/:splat"
  status = 200


[[redirects]]
  from = "/static/media/uploads/*"
  to = "http://ec2-18-118-138-187.us-east-2.compute.amazonaws.com/static/media/uploads/:splat"
  status = 200